name: news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-VariableFont_wght.ttf
        
